
# Basic
name:               "MACIVER LAB"
title:              "laboratory of info-mechanics and neuroethology"
description:        "this is the page for MacIver Lab, we are a neuroethology lab under Neuroscience and Robotics (NxR) Lab based in Northwestern University, Evanston"



# URL
url:                http://maciverlab.github.io
baseurl:            /
#baseurl:            "" #For Root Domain
permalink:          /:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "HOME"
    href:           "/"
  - name:           "PROJECTS"
    href:           "/projects"
  - name:           "DATA"
    href:           "/data"
  #- name:           "RESEARCH"
  #  href:           "/research"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "projdata"
    values:
      layout:       "post"


collections:
  projects:
    output: true
    permalink: /projects/:categories/:title.html
  projdata:
    output: true
    permalink: /data/:categories/:title.html
#  people:
#    output: true
#    permalink: /people/:title/index.html
