
# Basic
name:               "Laboratory of info-mechanics and neuroethology"
title:              "MacIver Lab"
description:        "this is the page for MacIver Lab, we are a neuroethology lab under Center for Robotics and Biosystems at the Northwestern University, Evanston"



# URL
url:                http://maciverlab.github.io
baseurl:            /
#baseurl:            "" #For Root Domain
permalink:          /:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  #- name:           "HOME"
  #  href:           "/"
  - name:           "ABOUT"
    href:           "/about"
  - name:           "PUBLICATIONS"
    href:           "/publications"
  - name:           "PEOPLE"
    href:           "/people"
  - name:           "RESEARCH"
    href:           "/research"
  - name:           "RESOURCES"
    href:           "/resources"
  - name:           "MEDIA"
    href:           "/media" 
  #- name:           "PROJECTS"
  #  href:           "/projects"
  #- name:           "DATA"
  #  href:           "/data"
  #- name:           "RESEARCH"
  #  href:           "/research"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "projdata"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  projects:
    output: true
    permalink: /projects/:categories/:title.html
  projdata:
    output: true
    permalink: /data/:categories/:title.html
#  people:
#    output: true
#    permalink: /people/:title/index.html
